### ISSUE TITLE
Witherstorm Flashes in distance

### ISSUE THREAD

**Issue by humzahre** [nonamecrackers2/crackers-wither-storm-mod#979] opened 2023-03-01 18:54 UTC
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**1.19.3**
The version of Minecraft the mod is running on

**3.2**
The version of the mod you are using

**In the distance, the Witherstorm is flashing.**

**To Reproduce**
1. teleport over 2000+ blocks away
2. move around and see WS flashing

**doesn't crash the game**
Crash reports / logs hosted on pastebin, gist, etc.

**no optifine**
Specify if you're using OptiFine

**

https://user-images.githubusercontent.com/125754458/222237619-b05113b5-f70e-4dd0-b453-980f2909ed1b.mp4

**

**Comment by Globalfirestorm10** [comment] 2023-03-01 20:53
What part of fill out the template properly do you not understand? It's just not even 1 minute of your time, I see no point why you don't fill it out.

**Comment by Globalfirestorm10** [comment] 2023-03-01 20:53
That aside, what other mods are you using?

**Comment by FrozenDragon0** [comment] 2023-03-02 01:39
> What part of fill out the template properly do you not understand? It's just not even 1 minute of your time, I see no point why you don't fill it out.

People are just incredibly lazy unfortunately.

**Comment by Globalfirestorm10** [comment] 2023-03-02 02:20
Yeah, looks that that laziness applies to lots of things nowadays

**Comment by myron-obsolete-account** [comment] 2023-03-02 16:11
why did you replace the subheaders with the data? you should've put the info below them. also you still didn't fill out the steps how to reproduce this issue, if you have flywheel and crash reports/logs. atleast there you could've put "N/A" as it doesn't seem necessary

**Comment by nonamecrackers2** [comment] 2023-03-02 16:33
We don’t need to get nit picky about how the information is put in. But yes, please fill out the entire template, it helps us diagnose issues better.

What is your mod list?

**Comment by Stongz** [comment] 2023-03-02 17:49
Yeah I've been having this issue as well, the Wither Storm (when rendered far away) would start blinking whenever I move around.

And no, I don't have OptiFine nor Flywheel installed.

**Comment by humzahre** [comment] 2023-03-02 20:19
I only have worldedit and CWSM

**Comment by humzahre** [comment] 2023-03-02 20:20
btw, I DID FILL OUT THE TEMPLATE!

**Comment by Globalfirestorm10** [comment] 2023-03-02 21:23
> btw, I DID FILL OUT THE TEMPLATE!

You didn't fully complete it. It takes a minute of your time to fill this in, it's not that hard

**Comment by nonamecrackers2** [comment] 2023-03-03 00:21
You didn’t fill in the steps to reproduce

**Comment by humzahre** [comment] 2023-03-03 19:48
idk what steps to reproduce are. srry

**Comment by humzahre** [comment] 2023-03-03 19:48
please help me with that

**Comment by humzahre** [comment] 2023-03-04 19:50
its filled now

**Comment by Globalfirestorm10** [comment] 2023-03-04 22:59
Congratulations, you managed to do something so simple.That aside, looks like this may be a bug after all

**Comment by humzahre** [comment] 2023-03-05 20:13
ty

**Comment by humzahre** [comment] 2023-03-06 19:49
now can u fix it nonamecrackers2?

**Comment by Globalfirestorm10** [comment] 2023-03-06 21:59
> now can u fix it nonamecrackers2?

have patience, he's not gonna instantly know what to fix.

**Comment by Globalfirestorm10** [comment] 2023-03-06 21:59
fixing bugs takes time, as you not only have to determine whats causing it and fix it, but you also must test the bugfixed version to see if it caused other bugs to happen

**Comment by humzahre** [comment] 2023-03-09 19:29
ok ok

**Comment by nonamecrackers2** [comment] 2023-03-11 23:42
Managed to figure out the bug

**Comment by humzahre** [comment] 2023-03-17 15:18
can u fix it?

**Comment by Globalfirestorm10** [comment] 2023-03-17 21:39
Again, please have some patience, it takes longer than you think to fix bugs

**Comment by humzahre** [comment] 2023-03-17 21:41
ok ok

**Comment by nonamecrackers2** [comment] 2023-03-27 23:21
Will be fixed in 2.2.1/3.2.1

**Closed as completed by nonamecrackers2** 2023-03-27 23:21 UTC
Labels: Bug/Errors, 1.18.2, 1.19.3
