### ISSUE TITLE
[Bug]: Cannot play in 1.20.1

### ISSUE THREAD

**Issue by SimonGamingPl** [nonamecrackers2/crackers-wither-storm-mod#1413] opened 2023-09-10 14:26 UTC
[2023-09-10-1.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12568480/2023-09-10-1.txt)
### Minecraft Version

1.20.1

### Mod Version

4.0

### Mod Loader

Forge

### Mod Loader Version

47.1.0

### Describe the bug

Evrytime i want to play on 1.20.1 it crashes (idk if this is a forge issue or what bc even when the mods folder is empty it still crashes)

Only works on 1.19.4 for me

![2023-09-10](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/82e35e0a-0973-432d-b748-85878079ab1f)

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![obraz_2023-09-10_162204950](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/6dc8e8de-7253-4cbd-87fb-c34e14786f07)

### Mod List

no

**Comment by TaintedBlock** [comment] 2023-09-10 14:26
Please submit a crash log

**Comment by SimonGamingPl** [comment] 2023-09-10 14:28
How?

**Comment by SimonGamingPl** [comment] 2023-09-10 14:30
> Please submit a crash log

how? i dont know how to.

( here is the crash log 
[2023-09-10-1.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12568491/2023-09-10-1.txt)

**Comment by CubeGamer647** [comment] 2023-09-10 14:37
%appdata%/.minecraft/logs and whatever session it was

**Comment by myron-obsolete-account** [comment] 2023-09-10 14:47
duplicate of #1409 
btw how even does that happen? incompatible mods? the error does not pop up for me

**Comment by SimonGamingPl** [comment] 2023-09-10 14:52
> duplicate of #1409 btw how even does that happen? incompatible mods? the error does not pop up for me

idk it dosent work even when the mods folder is empty

(btw hare is the crash log )
[2023-09-10-1.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12568488/2023-09-10-1.txt)

**Comment by myron-obsolete-account** [comment] 2023-09-10 14:56
it could be possible you are using a broken forge version, I believe this issue already appeared before
try using forge 47.1.44, that's the version I use and it works just fine

**Comment by SimonGamingPl** [comment] 2023-09-10 15:06
![obraz_2023-09-10_170650152](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/d6617ef6-c639-4139-8cc9-44d478232f39)
> it could be possible you are using a broken forge version, I believe this issue already appeared before try using forge 47.1.44, that's the version I use and it works just fine

No it dosent work 
[2023-09-10-1.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/12568514/2023-09-10-1.txt)

**Comment by myron-obsolete-account** [comment] 2023-09-10 15:16
huh.
CWSM is the only mod you have right?

**Comment by SimonGamingPl** [comment] 2023-09-10 16:09
> huh. CWSM is the only mod you have right?

I have two, one for 1.20.1 and for 1.19.4. If you think that im putting wrong file into mods your wrong cuss im playing on 1.19.4 now
![obraz_2023-09-10_180911322](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/4a2f9baf-7bf3-44b7-95fe-43841f9044cd)
![obraz_2023-09-10_180927429](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/143898670/692ab5a4-e3d4-444e-b603-febe98ebd49c)

**Comment by nonamecrackers2** [comment] 2023-09-10 19:23
What you provided is the log, not the crash report. Please send the crash report, it should be in `crash-reports`

**Comment by FartasticYYZ** [comment] 2023-09-11 01:04
I got the same exact bug but for me I cant run forge on versions 1.19.4 and higher. I have no mods installed on that forge file.

**Comment by nonamecrackers2** [comment] 2023-09-11 02:58
Unfortunately there isn't much that we can do without a crash report

**Comment by FartasticYYZ** [comment] 2023-09-11 03:23
Nevermind! I know a fix. If you have crash issues with error code 1 then you most likely have an amd graphic card. All you have to do is go on their support website and install a driver update software adrenaline and update your drivers. It worked for me

**Comment by SimonGamingPl** [comment] 2023-09-11 15:42
> Nevermind! I know a fix. If you have crash issues with error code 1 then you most likely have an amd graphic card. All you have to do is go on their support website and install a driver update software adrenaline and update your drivers. It worked for me

OMG thank you! it worked!

**Closed as completed** 2023-09-11 16:06 UTC
Labels: Bug/Errors, More Info Needed, 1.20.1, NO CRASH LOG!

**Comment by nonamecrackers2** [comment] 2023-09-11 18:51
Ah alright, glad that was the cause
