### ISSUE TITLE
[Wither Storm crashes some custom worlds on spawn] Bug Wither Storm

### ISSUE THREAD

**Issue by Loverxzc** [nonamecrackers2/crackers-wither-storm-mod#36] opened 2022-05-26 11:13 UTC
just look
https://youtu.be/Xyddo6Hzj5Y
and
![Screenshot_117](https://user-images.githubusercontent.com/105715466/170477178-228d930c-f5b3-4ddf-a552-ff1fef2ba95c.png)
![Screenshot_118](https://user-images.githubusercontent.com/105715466/170477186-0fcf7cdc-94f5-449d-91bc-902ab906dab3.png)

**Comment by Loverxzc** [comment] 2022-05-26 11:17
On 1 screenshot "Saving World"

**Comment by nonamecrackers2** [comment] 2022-05-26 18:23
Yeah this is because of how it loads the bowels arena when it's first summon... some people have their entire game crash when this happens. I'll have to come up with something to fix this (btw like the map)

**Comment by nonamecrackers2** [comment] 2022-07-04 16:14
I'm unable to reproduce this issue. Could you send the map you were using?

**Comment by nonamecrackers2** [comment] 2022-07-04 17:12
Closing until this issue can be reliably reproduced

**Closed as completed** 2022-07-04 17:12 UTC
Labels: Bug/Errors, 1.16.5, Can't Reproduce

**Comment by Loverxzc** [comment] 2022-09-28 16:10
> Closing until this issue can be reliably reproduced
1. Just create flat world without mod.
2. Load forge and mod.
3. See problem.
I think, you should add the funciton for re-load bowels.

**Comment by nonamecrackers2** [comment] 2022-09-29 17:21
If the world you created has structures enabled, summoning a wither storm will cause the game to hang infinitely. You’ll need to find a way to enable structures.

**Comment by Loverxzc** [comment] 2022-09-30 11:00
> If the world you created has structures enabled, summoning a wither storm will cause the game to hang infinitely. You’ll need to find a way to enable structures.

Yeah, it's working.
