### ISSUE TITLE
[Suggestion]: Enhanced music

### ISSUE THREAD

**Issue by lelenski** [nonamecrackers2/crackers-wither-storm-mod#1824] opened 2024-03-28 20:17 UTC
### Description of feature request

When the wither storm is in the distance and you are getting closer/its getting closer to you, music will build up and the closer you/it gets the more intense the music gets

**Comment by BluePineappleGuy** [comment] 2024-03-28 20:23
duplicate of #227

**Comment by lelenski** [comment] 2024-03-28 20:24
oh im sorry

**Closed as not planned** 2024-03-28 20:25 UTC
Labels: Duplicate, Suggestion
