### ISSUE TITLE
[Suggestion]: command block bow

### ISSUE THREAD

**Issue by floppydiskdrive6** [nonamecrackers2/crackers-wither-storm-mod#1501] opened 2023-09-25 20:33 UTC
### Description of feature request

a weapon that can damage the command block but from a distance like a bow maybe even a crossbow

**Comment by Laughingcat27** [comment] 2023-09-25 20:37
that would be very overpowered since you won't have to avoid getting smacked by the tentacles guarding the command block

**Comment by LegendaryGodzilla** [comment] 2023-09-25 20:44
nah

**Comment by TaintedBlockmObile** [comment] 2023-09-25 20:54
This kinda kills the whole boss battle tbh.

**Comment by floppydiskdrive6** [comment] 2023-09-26 04:06
you could make so theres only a 25% chance it damages the command block

**Comment by floppydiskdrive6** [comment] 2023-09-26 04:07
and if it doesn't work it wont work until the next phase

**Comment by floppydiskdrive6** [comment] 2023-09-26 04:13
bc bows are weak

**Comment by floppydiskdrive6** [comment] 2023-09-26 04:58
+ the boss keeps getting harder

**Comment by floppydiskdrive6** [comment] 2023-09-26 06:17
every update

**Comment by TaintedBlockmObile** [comment] 2023-09-26 08:12
> bc bows are weak

Then that just makes the bow useless

**Comment by myron-obsolete-account** [comment] 2023-09-26 13:24
duplicate of #857

**Closed as not planned** 2023-09-28 02:32 UTC
Labels: Duplicate, Suggestion

**Comment by floppydiskdrive6** [comment] 2023-09-28 05:51
i didn't know this was a duplication💀
