### ISSUE TITLE
A possible way to make tractor beams more forgiving

### ISSUE THREAD

**Issue by GrandmaPork** [nonamecrackers2/crackers-wither-storm-mod#514] opened 2022-08-15 14:04 UTC
It is very common for the other wither storm heads to catch a player after they escape from one beam. One solution could be to give the entity an effect like "wither storm head 1" and if they have that effect, they can't be targeted by another head. 
While playing, I noticed that if one head picked up a cluster of mobs, the other heads would target different mobs that are already being beamed up causing the group to split apart (which isn't that bad) but can be annoying if you escape one head only to be targeted by the next.

**Comment by RandomGithubUser32** [comment] 2022-08-15 17:30
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/290

**Comment by nonamecrackers2** [comment] 2022-08-15 20:30
I've noted the targeting other mobs already being beamed up, but since this is primarily a duplicate of #290 I will close this.

**Closed as completed by nonamecrackers2** 2022-08-15 20:30 UTC
Labels: Duplicate, Suggestion
