### ISSUE TITLE
Moving Tractor Beams

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#915] opened 2023-02-15 15:31 UTC
Instead Of Instantly Focusing On One Mob It Should Move The Tractor Beam And Search Until It Finds A Mob

**Comment by myron-obsolete-account** [comment] 2023-02-15 16:56
duplicate of #208 #285 please close

P.S.: How is it possible that you have learned nothing in the past few issues here? You should know by now that it's better to look for similar issues or issues with the same topic before making a new one, it just slowly starts to get annoying.
Literally stated in the guidelines #217:
> **Please go through this before you make a feature suggestion.**
>...**Make sure to check to see if yours also already been submitted.**

There are 5 issues by you that have been closed as a duplicate. This will be the 6th. The next time you want to suggest something PLEASE look for it first.

**Comment by LucasDotje** [comment] 2023-02-15 18:46
I Did Look It Up

**Closed as completed** 2023-02-15 18:46 UTC
Labels: Suggestion

**Comment by nonamecrackers2** [comment] 2023-02-16 01:33
Admittedly it is time consuming to look through everything.
