### ISSUE TITLE
[Performance] Wither Storm Heads in Boss Fight tank FPS when you're around their mouth

### ISSUE THREAD

**Issue by watersofnazareth** [nonamecrackers2/crackers-wither-storm-mod#133] opened 2022-06-24 21:56 UTC
I dunno how to really write a description, it's a really weird issue causing a major performance drop in the fight when looking at the head near the mouth

**Comment by nonamecrackers2** [comment] 2022-06-24 22:22
What version were you noticing this?

**Comment by nonamecrackers2** [comment] 2022-06-25 18:32
Unable to reproduce. Closing this for now. Do you have any other mods installed?

**Closed as completed by nonamecrackers2** 2022-06-25 18:32 UTC
Labels: Bug/Errors

**Comment by watersofnazareth** [comment] 2022-06-27 00:35
It may be something with Radium
