### ISSUE TITLE
multiplayer client crash

### ISSUE THREAD

**Issue by SplendidSuperGithub** [nonamecrackers2/crackers-wither-storm-mod#907] opened 2023-02-11 01:33 UTC
#
[crash-2023-02-10_18.32.34-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10712281/crash-2023-02-10_18.32.34-client.txt), i don't understand what happend, please help

**Comment by Globalfirestorm10** [comment] 2023-02-11 02:15
use the recommended version of CWSM,as the latest one features a bug that does this

**Comment by Globalfirestorm10** [comment] 2023-02-11 02:16
Also a duplicate of #885, please close this

**Comment by nonamecrackers2** [comment] 2023-02-16 01:25
#885 use the recommended version of forge for your version.

**Closed as completed by nonamecrackers2** 2023-02-16 01:25 UTC
