### ISSUE TITLE
Black Everything

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1417] opened 2023-09-10 16:31 UTC
### Minecraft Version

1.19.4

### Mod Version

3.3

### Mod Loader

Forge

### Mod Loader Version

1.19.4, 45.1.0

### Describe the bug

A bug happened!

### Steps to Reproduce

Run /witherstormmod phase set @w 4.5
Run /reload

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots
![Screen Shot 2023-09-11 at 11 34 23 AM](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114886300/621f52eb-f444-47d2-9ea0-1007e49b610a)

### Mod List

Cracker's Wither Storm Mod

**Comment by nonamecrackers2** [comment] 2023-09-10 19:24
Please provide some screenshots

**Comment by watersofnazareth** [comment] 2023-09-10 19:55
Well the issue is you're using 1.19.4 on 1.19.2

**Comment by nonamecrackers2** [comment] 2023-09-11 02:51
Oh yeah I didn't realize that

**Comment by nonamecrackers2** [comment] 2023-09-11 22:27
Strange. It appears your using some sort of resourcepack, could you list the resource packs you are using?

**Comment by WitherBean** [comment] 2023-09-12 00:13
Witherstormmod New Textures.

**Comment by nonamecrackers2** [comment] 2023-09-13 14:57
Have you tried removing them to see if that solves the issue?

**Comment by nonamecrackers2** [comment] 2023-10-06 18:19
Closing until more information is given

**Closed as not planned by nonamecrackers2** 2023-10-06 18:19 UTC
Labels: Bug/Errors, More Info Needed, 1.19.4
