### ISSUE TITLE
[Bug]: Wither Sickness is stopped

### ISSUE THREAD

**Issue by Gamerling8298** [nonamecrackers2/crackers-wither-storm-mod#1806] opened 2024-03-17 21:10 UTC
### Minecraft Version

1.20.1

### Mod Version

4.0.1.1

### Mod Loader

Forge

### Mod Loader Version

47.2.20

### Describe the bug

Whenever I enter the end portal that leads to the overworld whilst having the wither sickness effect, the effect disappears completely

### Steps to Reproduce

1) Get wither sickness effect
2) enter the end portal
3) enter the portal that leads back to the overworld

*I don't think it always cancels out the effect

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

Dynamic Lights

**Comment by FrozenDragon0** [comment] 2024-03-17 23:47
Duplicate of https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1788

**Closed as not planned** 2024-03-18 03:54 UTC
Labels: Bug/Errors, Duplicate
