### ISSUE TITLE
Wither Storm Body Unload

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#939] opened 2023-02-22 19:23 UTC
When You Kill The Wither Storm The Body Unloads During The Animation

**Comment by nonamecrackers2** [comment] 2023-02-22 19:30
Mind sending some screenshots? And providing more info such as game, mod and forge version?

**Comment by LucasDotje** [comment] 2023-02-22 19:39
![glitch](https://user-images.githubusercontent.com/121522736/220740656-62eb72d2-5840-4fb8-8373-074be157967a.png)

I Use The 1.18.2 New Update

**Comment by nonamecrackers2** [comment] 2023-02-22 22:18
Is this with optifine?

**Comment by myron-obsolete-account** [comment] 2023-02-23 14:34
This issue is present in 1.19.3 aswell and apparently the issue is not caused by OptiFine as I am not using OptiFine.

**Comment by LucasDotje** [comment] 2023-02-23 15:04
I Didn't Use Optifine

**Comment by Globalfirestorm10** [comment] 2023-02-26 00:55
this also happens with optifine on 1.19.3 during any phase at any time. The body is culled, and only the heads, tractor beams, and tentacles can be seen. I think this may be due to entity culling, but idk

**Comment by nonamecrackers2** [comment] 2023-02-27 16:50
Do you have an AMD or Nvidia based gpu?

**Comment by Globalfirestorm10** [comment] 2023-02-27 17:53
> Do you have an AMD or Nvidia based gpu?

me? Or the guy who opened this?

**Comment by nonamecrackers2** [comment] 2023-02-28 15:02
Both of you would be extremely helpful

**Comment by Globalfirestorm10** [comment] 2023-02-28 17:06
ah I see, I have an zotac rtx 3080 ti with the latest geforce experience drivers

**Comment by myron-obsolete-account** [comment] 2023-02-28 17:50
> Both of you would be extremely helpful

beh this issue likely happens to everyone I think. I have a Nvidia based GPU and tha issue applies to me too. Also about #972 they didn't talk about a death sequence so that may be a different issue. This one also happens without shaders. So those are 2 different issues I think.

**Comment by Globalfirestorm10** [comment] 2023-02-28 21:40
> > Both of you would be extremely helpful
> 
> 
> 
> beh this issue likely happens to everyone I think. I have a Nvidia based GPU and tha issue applies to me too. Also about #972 they didn't talk about a death sequence so that may be a different issue. This one also happens without shaders. So those are 2 different issues I think.

Yeah it's an optifine problem

**Comment by nonamecrackers2** [comment] 2023-03-01 15:05
I believe some people said they experienced this without optifine as well, very peculiar bug, I will have to investigate

**Comment by TeaCupsTeaPots** [comment] 2023-03-01 16:04
yes i can confirm this is with and without optifine

**Comment by Stanislav228Bebrochka** [comment] 2023-03-03 16:56
Same problem

**Comment by Stanislav228Bebrochka** [comment] 2023-03-03 17:49
> > > Both of you would be extremely helpful
> > 
> > 
> > beh this issue likely happens to everyone I think. I have a Nvidia based GPU and tha issue applies to me too. Also about #972 they didn't talk about a death sequence so that may be a different issue. This one also happens without shaders. So those are 2 different issues I think.
> 
> Yeah it's an optifine problem

I dont use optifine only rubidium but i have same problem

**Comment by Stanislav228Bebrochka** [comment] 2023-03-03 17:50
Also it happening without any mod, on any version

**Comment by nonamecrackers2** [comment] 2023-03-04 22:23
May I ask what's your operating system? Trying to see if there's something common amongst the users who are experiencing this problem

**Comment by Globalfirestorm10** [comment] 2023-03-04 22:58
> May I ask what's your operating system? Trying to see if there's something common amongst the users who are experiencing this problem

I noticed that with optifine, the body of the ws (starting phase 1 and above) is a semi-transparent grey, and completely invisible during shaders

**Comment by Stanislav228Bebrochka** [comment] 2023-03-05 11:10
I have same problem

**Comment by myron-obsolete-account** [comment] 2023-03-05 16:28
> May I ask what's your operating system? Trying to see if there's something common amongst the users who are experiencing this problem

Windows 10 Home 😎

**Comment by Globalfirestorm10** [comment] 2023-03-05 17:43
> > May I ask what's your operating system? Trying to see if there's something common amongst the users who are experiencing this problem
> 
> 
> 
> Windows 10 Home 😎

same

**Comment by TeaCupsTeaPots** [comment] 2023-03-05 21:11
> > > May I ask what's your operating system? Trying to see if there's something common amongst the users who are experiencing this problem
> > 
> > 
> > Windows 10 Home 😎
> 
> same

same

**Comment by nonamecrackers2** [comment] 2023-03-06 15:59
Interesting, will have to try out the mod on another computer running windows 10 since I’m using 11

**Comment by myron-obsolete-account** [comment] 2023-03-06 16:13
> Interesting, will have to try out the mod on another computer running windows 10 since I’m using 11

No offense but ewww Windows 11...🤺
(Please take this as a simple joke, duh.)

**Comment by Globalfirestorm10** [comment] 2023-03-06 18:19
> > Interesting, will have to try out the mod on another computer running windows 10 since I’m using 11
> 
> 
> 
> No offense but ewww Windows 11...🤺
> 
> (Please take this as a simple joke, duh.)

Moron, you should totally join crackers' discord server, you'd be great there

**Comment by myron-obsolete-account** [comment] 2023-03-07 16:36
> > > Interesting, will have to try out the mod on another computer running windows 10 since I’m using 11
> > 
> > 
> > No offense but ewww Windows 11...🤺
> > (Please take this as a simple joke, duh.)
> 
> Moron, you should totally join crackers' discord server, you'd be great there

Uhh maybe in lets say 10 years where society finally collapsed.

(no seriously I had some bad times on Discord and want to stay away from that platform for a while until the old wounds are fully closed)

I may consider joining in the future

**Comment by myron-obsolete-account** [comment] 2023-03-07 16:44
My god this issue is about to become number one in having the most comments
![image](https://user-images.githubusercontent.com/53058491/223490013-8cd40d3d-98b4-4e3b-abf3-4add7042f48e.png)

**Comment by humzahre** [comment] 2023-03-15 19:31
not just when you kill it
BUT ALSO WHEN ITS ALIVE THERE IS NO TORSO

**Comment by myron-obsolete-account** [comment] 2023-03-15 19:44
> not just when you kill it BUT ALSO WHEN ITS ALIVE THERE IS NO TORSO

no way thats literally what we're talking about in other issues the entire time duh

**Comment by humzahre** [comment] 2023-03-16 16:31
i have rtx 3050 ti

**Comment by nonamecrackers2** [comment] 2023-03-18 17:05
A problem with any shaders in general, a work around will be implemented when shaders are running

**Comment by TeaCupsTeaPots** [comment] 2023-03-19 00:40
has nothing to do with shaders at least not for me

**Comment by nonamecrackers2** [comment] 2023-03-27 23:07
> has nothing to do with shaders at least not for me

If you could open up a new issue for that that would be helpful

**Comment by nonamecrackers2** [comment] 2023-03-27 23:22
Will be fixed in 2.2.1/3.2.1

**Closed as completed by nonamecrackers2** 2023-03-27 23:22 UTC
Labels: Bug/Errors, 1.18.2, 1.19.3

**Comment by TeaCupsTeaPots** [comment] 2023-03-28 15:00
> > has nothing to do with shaders at least not for me
> 
> If you could open up a new issue for that that would be helpful

sure
