### ISSUE TITLE
Wither Storm crashes game when near players on server 1.19

### ISSUE THREAD

**Issue by MichaelBrad** [nonamecrackers2/crackers-wither-storm-mod#429] opened 2022-08-02 19:00 UTC
**Minecraft version**
1.19

**Mod version**
witherstormmod-1.19-3.0-beta.jar

**Describe the bug**
When using the mod on our Pebblehost server with forge installed, after spawning the wither storm and letting it go through its initial exploding stage before it starts moving, it'll kick me and my friend from the game giving this error message.

Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(55) + length(1) exceeds writerIndex(55):PooledUnsafeDirectByteBuf(ridx: 55, widx: 55, cap: 55)

This seems to only be a error on servers, as it works fine in singleplayer

**To Reproduce**
1. Make server (Not sure if Pebble Host uses linux, but I'm sure they do)
2. Make it use forge 41.0.99 and add the wither storm mod
3. Spawn the witherstorm at the small hut, wait for it to explode and to start moving
4. The error will occur

**Crash Reports / Logs**
[Crash reports / logs hosted on pastebin, gist, etc.](https://pastebin.com/nXU2BS9d)

**Screenshots**
![save](https://user-images.githubusercontent.com/51562934/182452790-6f2377cd-ec71-435e-9e4f-ad58dc46fb04.PNG)

**Comment by nonamecrackers2** [comment] 2022-09-18 19:55
I'm unfortunately unable to reproduce this issue. Could you send over your entire modlist?

**Comment by watersofnazareth** [comment] 2022-09-27 21:51
Closing this till more info is given

**Closed as completed by watersofnazareth** 2022-09-27 21:51 UTC
Labels: Bug/Errors, More Info Needed, Can't Reproduce, 1.19
