### ISSUE TITLE
Wither Storm ignores Formidi-Bomb even when ignited

### ISSUE THREAD

**Issue by AaronDeadKey** [nonamecrackers2/crackers-wither-storm-mod#800] opened 2022-12-11 10:46 UTC
**Minecraft version**
1.19.2

**Mod version**
3.1.1

**Describe the bug**
As title says, the Wither Storm doesn't pick up the formidi-bomb after I ignited it. I also saw on discord that someone posted the same issue. I'm not sure if someone else encountered this bug, but I'm one of the people who also experienced the same thing.

**To Reproduce**
1. Spawn the Wither Storm
2. Set it to Phase 5
3. Place and light the formidi-bomb
4. Wait and see

**Crash Reports / Logs**
No crashes

**Is Flywheel's optimizations active?**
No. Flywheel is still in 1.18.2 for now.

**Screenshots**

![2022-12-11_18 41 41](https://user-images.githubusercontent.com/120308800/206899080-a8c77610-5bf1-4896-baab-2d56e1f94c90.png)

**Comment by Globalfirestorm10** [comment] 2022-12-12 02:34
this is a known bug, please close the issue

**Closed as completed** 2022-12-12 10:06 UTC

**Comment by V0calgiant12** [comment] 2022-12-12 16:09
yes, this is a duplicate of #736
