### ISSUE TITLE
Witherstorm despawns in server after long period of inactivity.

### ISSUE THREAD

**Issue by ShirakiShio** [nonamecrackers2/crackers-wither-storm-mod#74] opened 2022-06-10 11:59 UTC
Whenever we log back onto the server in the morning to play on the server, the witherstorm is not on the horizon, and attempts to /kill it returns "No Entity found". We assume it has despawned. We are forced to OP ourselves and respawn it at phase 5 on 0 0, it is quite inconvenient since we are gonna travel further distances soon. The entity might still exist and just isn't within range, which could cause some issues (namely, extreme lag.)

I stop the server after we end for the day at approx. 2 AM, I start it back up at approx. 2pm.

Any way this can be prevented via. settings or similar?

**Comment by Loverxzc** [comment] 2022-06-10 12:30
This is due to the server different from the single game. If you just close a console, server incorrect saves the world, try write in console "stop". It is helps me.

**Comment by nonamecrackers2** [comment] 2022-06-10 17:15
It may still exist but just refuses to load, never had this happen (probably because I leave my servers running). I'll have to take a look. You could check if it exists by doing /witherstormmod chunks get

**Comment by ShirakiShio** [comment] 2022-06-10 23:18
I will check it tomorrow morning, thank you.

nonamecrackers2 ***@***.***> schrieb am Fr., 10. Juni 2022,
19:15:

**Comment by ShirakiShio** [comment] 2022-06-11 10:59
![image](https://user-images.githubusercontent.com/48332495/173185093-3e351561-88ff-4a0f-b117-722448ab890a.png)

**Comment by nonamecrackers2** [comment] 2022-06-11 15:21
You'll need to execute the command in the overworld, /execute in minecraft:overworld run witherstormmod chunks get

**Comment by ShirakiShio** [comment] 2022-06-11 15:25
I have shortly after, it returned the same message.

**Comment by nonamecrackers2** [comment] 2022-06-11 15:26
I'm investigating it now. Not sure why this is happening

**Comment by nonamecrackers2** [comment] 2022-06-11 15:29
Okay, I managed to reproduce it

**Comment by ShirakiShio** [comment] 2022-06-11 15:33
I'm not entirely sure if all of it is related specifically to the mod, I see a few lines where it is, but the server console is throwing some (fatal) errors at me, I'll send them here nonetheless if it helps in any way.

first it throws this at me


[15:29:26] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/GameRenderer for invalid dist DEDICATED_SERVER
[15:29:26] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/GameRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/GameRenderer for invalid dist DEDICATED_SERVER)
[15:29:26] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.GameRenderer was not found witherstormmod.mixins.json:IMixinGameRenderer
[15:29:26] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/model/ModelRenderer (java.lang.ClassNotFoundException: null)
[15:29:26] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.model.ModelRenderer was not found witherstormmod.mixins.json:IMixinModelRenderer
[15:29:26] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/GameRenderer for invalid dist DEDICATED_SERVER
[15:29:26] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/GameRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/GameRenderer for invalid dist DEDICATED_SERVER)
[15:29:26] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.GameRenderer was not found witherstormmod.mixins.json:MixinGameRenderer
[15:29:26] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/shader/ShaderGroup for invalid dist DEDICATED_SERVER
[15:29:26] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/shader/ShaderGroup (java.lang.RuntimeException: Attempted to load class net/minecraft/client/shader/ShaderGroup for invalid dist DEDICATED_SERVER)
[15:29:26] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.shader.ShaderGroup was not found witherstormmod.mixins.json:IMixinShaderGroup
[15:29:26] [main/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/BlockModelRenderer for invalid dist DEDICATED_SERVER
[15:29:26] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/BlockModelRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/BlockModelRenderer for invalid dist DEDICATED_SERVER)
[15:29:26] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.BlockModelRenderer was not found witherstormmod.mixins.json:IMixinBlockModelRenderer

and then shortly after

[15:29:37] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, {REMOVED BY AUTHOR}]
[15:29:37] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:29:37] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:29:37] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, {REMOVED BY AUTHOR}]
[15:29:37] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[15:29:37] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [witherstormmod, bowels, new] and [witherstormmod, bowels, entity] with inputs: [new]
[15:29:37] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [witherstormmod, cluster, create, pos] and [witherstormmod, cluster, create, start] with inputs: [^1 ^ ^-5, 0 0 0, ~ ~ ~, ^ ^ ^, ~0.5 ~1 ~-5]
[15:29:37] [main/WARN] [minecraft/Commands]: Ambiguity between arguments [witherstormmod, cluster, create, start] and [witherstormmod, cluster, create, pos] with inputs: [^1 ^ ^-5, 0 0 0, ~ ~ ~, ^ ^ ^, ~0.5 ~1 ~-5]

Hope this helps.

**Comment by nonamecrackers2** [comment] 2022-06-11 15:34
Oh yeah those can be ignored

**Comment by ShirakiShio** [comment] 2022-06-11 15:37
gotcha

**Comment by nonamecrackers2** [comment] 2022-06-11 15:45
Should be fixed now, I'll get an update pushed out in the next little bit.

**Closed as completed by nonamecrackers2** 2022-06-11 15:45 UTC
Labels: Bug/Errors, 1.16.5

**Comment by ShirakiShio** [comment] 2022-06-11 15:47
thanks a bunch! I appreciate your investment and communication.

**Comment by nonamecrackers2** [comment] 2022-06-11 15:51
Np

**Comment by nonamecrackers2** [comment] 2022-06-11 16:51
Just got an update with the fix out https://www.curseforge.com/minecraft/mc-mods/crackers-wither-storm-mod/files/3827853

**Comment by ShirakiShio** [comment] 2022-06-11 17:06
thank you! I'll check it out.

**Comment by ShirakiShio** [comment] 2022-06-12 10:08
![image](https://user-images.githubusercontent.com/48332495/173228235-2626cd36-80a4-494e-8ff9-ed73efd1e336.png)
works! awesome stuff.
