### ISSUE TITLE
distant rendering issue

### ISSUE THREAD

**Issue by SSgamingYT** [nonamecrackers2/crackers-wither-storm-mod#125] opened 2022-06-19 05:24 UTC
for some reason when the wither storm changes into the stage 5 level that can be blown up, the distant rendering system makes it still appear as the normal stage 5, instead of the larger version. this also occurs with stage 7, as the main wither storm appears as the stage 6 wither storm, while still having the three heads.

**Comment by nonamecrackers2** [comment] 2022-06-19 14:42
What mod version?

**Comment by ShirakiShio** [comment] 2022-06-24 16:10
oh yes I had this happen too. I think this issue was occuring for me on 1.16.5, latest mod version. I think I used a command to change the consumed entities which fixed it. Though in my case it was reversed (I believe), it showed the end of phase 5 in the distance, while close up it was just mid phase 5.

**Comment by nonamecrackers2** [comment] 2022-06-24 16:43
It might be some desync, will have to investigate

**Comment by nonamecrackers2** [comment] 2022-07-04 17:11
I'm unable to reproduce this issue... If you could somehow find a way to reliably reproduce this issue, I could potentially fix it (otherwise I have no idea how). My only guess would be optifine's "Smooth World" performance option, as it causes the WS to unload in spawn chunks, and that could maybe somehow have caused some weird desync or "ghost" wither storm that wouldn't get updated (possibly the source of desync?). This issue could also happen without optifine, or maybe it doesn't even need to be in the spawn chunks. I'm going to close this until this issue can be reliably reproduced.

**Closed as completed by nonamecrackers2** 2022-07-04 17:11 UTC
Labels: Bug/Errors, 1.16.5, Can't Reproduce
