### ISSUE TITLE
Anvil instead of Smithing Table

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1140] opened 2023-04-23 16:22 UTC
Unlike all enchanted books, the command block book is in a smithing table.

**Comment by NinjaSam5399** [comment] 2023-04-23 17:38
Uhh, I don't think this is a normal suggestion.

**Comment by NinjaSam5399** [comment] 2023-04-23 17:49
Can you please be more serious about suggestions.

**Comment by darkheart78** [comment] 2023-04-23 17:54
It is serious?

**Comment by myron-obsolete-account** [comment] 2023-04-23 18:01
> It is serious?

no you said "FIX FIX FIX FIX DID XIF CIF DIF XIF XIF XIF XIFF CIXNDIXJCNFCICJ" but there's nothing to fix so ehhhh... redo your suggestion with more professionalism please

**Comment by IndigoAmethyst** [comment] 2023-04-24 07:08
Yeah that will have to happen because of 1.20.

**Comment by BluePineappleGuy** [comment] 2023-04-25 05:52
maybe might not happen, for what i know about the anvil its used to change nbt of an item using another (like changing the item name, enchantments, or durability), wheras the smithing table is the same except it changes the item itself, preserving the nbt of the item. considering it should change it from diamond tool to command block tool, an anvil probably wouldn't work. so adding a smithing template is probably what crackers will have to do.

**Comment by IndigoAmethyst** [comment] 2023-05-08 15:10
Unless the tools become nbt based.

**Comment by IndigoAmethyst** [comment] 2023-05-08 15:12
#1139

**Comment by BluePineappleGuy** [comment] 2023-05-08 16:54
> Unless the tools become nbt based.

that would require a whole rework of the tools themselves, as command block tools opening the bowels hole and hitting the command block is dependent on the tag 'witherstormmod:command_block_tools' for datapack compatibility. along with other properties around the tools, such as attack damage and particles, this would be extremely difficult.

**Comment by NinjaSam5399** [comment] 2023-05-15 15:01
#1139

**Comment by nonamecrackers2** [comment] 2023-05-15 16:10
> #1139

I’m counting this as a separate issue as that one is more so requesting a completely new anvil if I decide to go that route.

**Comment by Steve982950** [comment] 2023-06-09 14:46
If this isn't confirmed, is it possible to make a SMITHING TEMPLATE for the new 1.20 update?

**Comment by LocalWaterCreeper911911** [comment] 2023-06-09 15:06
> If this isn't confirmed, is it possible to make a SMITHING TEMPLATE for the new 1.20 update?

this should be possible, its not confirmed yet so patience

**Comment by IndigoAmethyst** [comment] 2023-06-11 19:36
> If this isn't confirmed, is it possible to make a SMITHING TEMPLATE for the new 1.20 update?

I suggested that, but Cracker said he is probably gonna use an anvil

**Comment by Steve982950** [comment] 2023-06-12 15:15
ok

**Comment by nonamecrackers2** [comment] 2023-10-06 17:44
Closing since the anvil is now the block to craft command block tools

**Closed as completed by nonamecrackers2** 2023-10-06 17:44 UTC
Labels: Suggestion, Misc
