### ISSUE TITLE
[Bug]: Eyes look injured when having "Render Emissive decal for heads" off. 

### ISSUE THREAD

**Issue by NinjaSam5399** [nonamecrackers2/crackers-wither-storm-mod#1940] opened 2024-05-18 00:03 UTC
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Minecraft Version

1.20.1

### Mod Version

4.1

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Describe the bug

When you disable emissive decal with shader, the head looks injured when its not.

### Steps to Reproduce

1. Install the shader with Embeddium, Oculus, and Complementary Unbound.
2. Summon the Wither storm at phase 4+.
3. Go to the wither storm settings > Client Options > Preference > Render Emissive Decal For Heads.
4. See error.

### Crash Reports/Logs

Didn't Crash

### Is OptiFine installed?

- [ ] OptiFine is installed

### Screenhots

![Base Profile Screenshot 2024 05 17 - 18 49 30 20](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/111523734/1411c011-d3dc-4c06-9a6d-05161b814e76)

### Mod List

Oculus
Embeddium
Just Enough Items (JEI)
Cracker's Wither Storm Mod

**Comment by NinjaSam5399** [comment] 2024-05-18 00:03
If you can't see the injured eyes, look more closer at the eyes.

**Comment by Magiciandseq3** [comment] 2024-05-18 08:59
I have that bug too

**Comment by TheRugIsGone** [comment] 2024-05-28 04:53
I BELIEVE that this is caused by the witherstorm's default eye model is the broken one. and it just puts a overlay on it to hide it

**Comment by nonamecrackers2** [comment] 2024-05-31 18:45
Yeah that would be why

**Comment by Herobrine982950291** [comment] 2024-06-29 20:16
This thing happens to me. only this time, the cracks are slightly Visible even with "Render Emissive decal for heads" on.

**Comment by FalconinVoid** [comment] 2024-07-11 07:13
> I BELIEVE that this is caused by the witherstorm's default eye model is the broken one. and it just puts a overlay on it to hide it

The teeth also loose their glow when the eye is broken XD

**Comment by Herobrine982950291** [comment] 2024-07-11 17:51
> > I BELIEVE that this is caused by the witherstorm's default eye model is the broken one. and it just puts a overlay on it to hide it
> 
> The teeth also loose their glow when the eye is broken XD

I think you meant XDDCC not XD

**Comment by nonamecrackers2** [comment] 2024-07-11 18:22
Will be fixed in the next major release

**Closed as completed by nonamecrackers2** 2024-07-11 18:22 UTC
Labels: Bug/Errors, 1.20.1

**Comment by FalconinVoid** [comment] 2024-07-12 07:01
:D
