### ISSUE TITLE
Better withered symbiont death animation

### ISSUE THREAD

**Issue by mattdafilipino** [nonamecrackers2/crackers-wither-storm-mod#1518] opened 2023-09-30 23:34 UTC
### Description of feature request

The death animation for the withered symbiont (exception for the bowels version) is kind of anti climatic and kinda just poofs into thin air like he's not in some sort of relation with the witherstorm. It should be more flashy like this decayed reality video below but obviously not over the top with visuals and audio.

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/103057495/33346a0d-9cdf-4bd3-9fed-dc0f417d3016

**Comment by TaintedBlockmObile** [comment] 2023-09-30 23:38
I do agree it should have a more dramatic death. It's very anticlimactic rn.

**Comment by Laughingcat27** [comment] 2023-09-30 23:47
if only cracker doesn't make this suggestion poof away like the symbiont does

**Comment by Pandaboi25x** [comment] 2023-10-01 07:25
Duplicate of #1122

**Closed as not planned** 2023-10-01 19:42 UTC
Labels: Duplicate, Suggestion
