### ISSUE TITLE
[Suggestion]: Wither Storm Head Icon on maps 

### ISSUE THREAD

**Issue by Infinitekaosv3** [nonamecrackers2/crackers-wither-storm-mod#2312] opened 2024-11-17 22:39 UTC
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

On maps it will show the Wither Storm's Head and where its located
Example: 
![image](https://github.com/user-attachments/assets/50f0257a-29e6-4a7a-b411-5db94f098f3e)
![image](https://github.com/user-attachments/assets/e74b7caa-94a9-438d-9c6d-cfc7e651ebb0)

**Comment by Infinitekaosv3** [comment] 2024-11-17 22:40
Also no I didnt make that WS head

**Comment by watersofnazareth** [comment] 2024-11-18 03:58
Going to label this a duplicate of #770 since it's the same general idea

**Closed as not planned by watersofnazareth** 2024-11-18 03:58 UTC
Labels: Suggestion

**Comment by Infinitekaosv3** [comment] 2024-11-18 04:01
> Going to label this a duplicate of #770 since it's the same general idea

Also I found out in one of decayed reality's sneak peak's, it has that same map with the purple stuff from github #770
