### ISSUE TITLE
Prop 4 On Command Block Sword 

### ISSUE THREAD

**Issue by Faknocker** [nonamecrackers2/crackers-wither-storm-mod#226] opened 2022-07-16 01:06 UTC
![Screenshot 2022-07-15 194228](https://user-images.githubusercontent.com/108953187/179328442-c2bc84a5-3470-453e-b93b-f289202137f5.png)
 For some reason I can put prop 4 on my command block sword??

**Comment by watersofnazareth** [comment] 2022-07-16 01:13
Vanilla feature of being in Creative mode, some enchants are incompatible

**Comment by nonamecrackers2** [comment] 2022-07-16 01:57
Searched it up and found a bug on the mc tracker describing this issue: https://bugs.mojang.com/browse/MC-95555. It's marked as working as intended.

**Closed as completed by nonamecrackers2** 2022-07-16 01:57 UTC
