### ISSUE TITLE
Mob Rotation in Tractor Beams

### ISSUE THREAD

**Issue by WitherBean** [nonamecrackers2/crackers-wither-storm-mod#1815] opened 2024-03-23 00:07 UTC
### Description of feature request

When the Wither Storm picks up mobs, it should have mobs rotate in the tractor beams like in mcsm. An example of this would be the block cluster rotation or <img width="825" alt="Screen Shot 2024-03-22 at 5 06 40 PM" src="https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/114886300/9ac9ba63-e1d3-45c9-90dd-3cfdeae9aa3c">

**Comment by Herobrine982950291** [comment] 2024-03-23 10:14
can be hard to code. Plus, NNC2 rarely adds MCSM stuff

**Comment by WitherBean** [comment] 2024-03-23 11:09
> can be hard to code. Plus, NNC2 rarely adds MCSM stuff

what is NNC2???

**Comment by Herobrine982950291** [comment] 2024-03-23 13:02
NoNameCrackers2

**Comment by BluePineappleGuy** [comment] 2024-03-23 20:21
duplicate of #1055

**Closed as not planned** 2024-03-27 18:04 UTC
Labels: Duplicate, Suggestion
