### ISSUE TITLE
Mod confliction: Dungeon Libraries  

### ISSUE THREAD

**Issue by Luke7381** [nonamecrackers2/crackers-wither-storm-mod#1303] opened 2023-07-26 22:25 UTC
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2

**Mod version**
"A Block and a hard place"

**Describe the bug**
Dungeon Libraries (and possibly its addon mods Dungeon Mobs and Dungeon Weapons) cause the wither storm's AI to bug out and act unpredictable. 
In the hunchback stages, the wither storm would mostly not attack mobs but randomly it would go after the nearest mob. It also ignores hostile mobs for some reason. The 2 smaller heads work fine.

In its Destroyer stages the Wither Storm acts normal somewhat. The heads occasionally does strange twitching motions and the tractor beams are misaligned when it happens.
Mod Links:
https://www.curseforge.com/minecraft/mc-mods/dungeons-libraries
https://legacy.curseforge.com/minecraft/mc-mods/dungeons-gear
https://legacy.curseforge.com/minecraft/mc-mods/dungeons-mobs

**To Reproduce**
1. Download Dungeon Libraries
2. Spawn the wither storm on any stage
3. Spawn any mob
4. See weird behavior

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.
none

**Is OptiFine installed?**
no

**Screenshots**

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/48260861/3541ff53-81cd-400a-8d3f-5a58115440e9

https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/48260861/1f7b977a-3a66-47d3-8305-6d388d3c6fe4

**Comment by nonamecrackers2** [comment] 2023-07-28 22:33
That is quite weird, I appreciate you sending videos of the problem. I'll take a look.

**Comment by nonamecrackers2** [comment] 2024-01-27 01:36
I'm unable to reproduce this issue. It's likely that the bug has been fixed on their end since this was opened.

**Closed as completed by nonamecrackers2** 2024-01-27 01:36 UTC
Labels: Compat, 1.18.2, Can't Reproduce

**Comment by Aimyx** [comment] 2024-01-27 06:45
>I am unable to reproduce.
bro same
