### ISSUE TITLE
WS Skulls travel forever and create an infinite trail of destruction.

### ISSUE THREAD

**Issue by TheD0ct0r101** [nonamecrackers2/crackers-wither-storm-mod#212] opened 2022-07-13 07:11 UTC
**Minecraft version**
1.18.2

**Mod version**
2.0.1.1

**Describe the bug**
Some of the Wither Skull projectiles that the WS shoots out will not disappear when they hit a block. Instead, they will kinda 'bounce' over and over across any and all terrain, and will cotninue to travel until they are outside the simulation distance.

**To Reproduce**
Unknown

**Crash Reports / Logs**
Not sure

**Screenshots**
One of the skulls in question, bouncing across the terrain like a dolphin
![2022-07-13_00 08 07](https://user-images.githubusercontent.com/11579139/178672909-e0c2b72c-9e74-4f1c-8a02-1dc12974577f.png)

Seen in this image is the trail of explosion holes that the skull projectile created as a result of bouncing across the land. Theres a huge mountain between here and the WS so it shouldn't have gotten to this point to begin with.
![2022-07-13_00 08 29](https://user-images.githubusercontent.com/11579139/178672930-236c1e76-39e7-42cf-9e3d-f544d7b99a5d.png)

**Comment by nonamecrackers2** [comment] 2022-07-14 20:09
This is extremely weird behavior that I'm unable to reproduce. What's your mod list? I have a feeling a mod may be the cause.

**Comment by andywowws** [comment] 2022-07-15 07:59
Probably some nbt tags of this skull went wrong

**Comment by TheD0ct0r101** [comment] 2022-07-15 17:30
> This is extremely weird behavior that I'm unable to reproduce. What's your mod list? I have a feeling a mod may be the cause.

Ahah, well im currently testing it in AllTheMods7, so the mod list is pretty huge.

**Comment by nonamecrackers2** [comment] 2022-07-16 17:57
Yeah. I feel like this may be a mod incompatibility, so I'll close this for now.

**Closed as completed by nonamecrackers2** 2022-07-16 17:57 UTC
Labels: Bug/Errors, More Info Needed, 1.16.5, 1.18.2
