### ISSUE TITLE
Hole to enter the bowels never appears under my current conditions

### ISSUE THREAD

**Issue by TheD0ct0r101** [nonamecrackers2/crackers-wither-storm-mod#211] opened 2022-07-13 06:59 UTC
**Minecraft version**
1.18.2

**Mod version**
2.0.1.1

**Describe the bug**
Hole to the bowels never appears even when on stage 7 (9 heads) and have one command block tool. The targetting mode is set to 'NONE', so I am curious if thats the cause. The WS has practically eaten its way down to bedrock and it still hasn't opened it's hole. It would be nice if I could play with the WS staying still and still have him actually be beatable.

**To Reproduce**
1. Change targetting to 'NONE'
2. Get to stage 7 and have a command block sword
3. Wait an eternity

**Crash Reports / Logs**
No crashes / errors of note

**Comment by nonamecrackers2** [comment] 2022-07-14 00:37
Yep, just realized that the “NONE” ultimate targeting type would be the cause

**Comment by TheD0ct0r101** [comment] 2022-07-14 01:26
I figured that was it but wasnt sure. Glad I mentioned it!

**Comment by nonamecrackers2** [comment] 2022-07-14 21:17
Will be fixed in the next update.

**Closed as completed by nonamecrackers2** 2022-07-14 21:17 UTC
Labels: Bug/Errors, 1.18.2
