### ISSUE TITLE
[Bug] Sickened Villager despawning isn't consistent with zombified villager despawning: 

### ISSUE THREAD

**Issue by Indeterminance** [nonamecrackers2/crackers-wither-storm-mod#1620] opened 2023-11-06 20:22 UTC
### Minecraft Version

1.20.1

### Mod Version

4.0.1

### Mod Loader

Forge

### Mod Loader Version

47.2.1

### Describe the bug

When zombifying a villager, the zombie villager is always **prevented from despawning** if it has previously been traded with. However, when villagers die of Wither Sickness after being traded with, the resulting **sickened villagers _can_ despawn**.

### Steps to Reproduce

1. Trade with a villager
2. Wait for the villager to die of Wither Sickness
3. Move away from the resulting sickened villager.
4. The sickened villager will despawn.

### Is OptiFine installed?

- [ ] OptiFine is installed

### Mod List

AppleSkin [2.5.1]
Corpse [1.0.5]
_Cracker's Wither Storm Mod_ [4.0.1]
Ferrite Core [6.0.0]
Mouse Tweaks [2.25]
Notes [1.3.0]
Oculus [1.6.9]
QuickStack [1.20.1-1]
Radium [0.12.1]
Rubidium [0.7.1]
Rubidium Dynamic Lights [1.6.0]
Rubidium Extra [0.5.2]
Simple Inventory Sorter [23.0.1]
Simple Zoom [1.0]
Xaero's Minimap [23.8.4]
Xaero's World Map [1.36.0]

**Comment by BluePineappleGuy** [comment] 2023-11-07 01:51
Maybe the issue is that the trade data isn't stored?

**Comment by nonamecrackers2** [comment] 2023-11-11 17:20
The trade data is stored, I believe it just doesn't check if it has trade data to prevent despawning

**Comment by nonamecrackers2** [comment] 2024-04-05 21:58
Will be fixed in the next major release

**Closed as completed by nonamecrackers2** 2024-04-05 21:58 UTC
Labels: Bug/Errors, 1.19.4, 1.20.1
