### ISSUE TITLE
Wither Storm targets players despite Symboint being alive

### ISSUE THREAD

**Issue by Inonedn** [nonamecrackers2/crackers-wither-storm-mod#363] opened 2022-07-24 23:03 UTC
**Minecraft version**
1.19

**Mod version**
Latest

**Describe the bug**
While the Storm is supposed to ignore you, it will target you despite the player going to fight the symboint

**To Reproduce**
1. Let a Storm spawn a symboint
2. Approach the wither storm
3. get sucked in
5. See error

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by RandomGithubUser32** [comment] 2022-08-27 23:13
The issue is that the tractor beams can still pull in entities that the wither storm should not be able to attack. I covered the issue in #560

**Comment by nonamecrackers2** [comment] 2022-08-30 00:25
This is fixed in the pre-release version, will come to the full release soon.

**Closed as completed by nonamecrackers2** 2022-08-30 00:25 UTC
Labels: Bug/Errors, 1.18.2, 1.19
