### ISSUE TITLE
Unable to place amulet painting

### ISSUE THREAD

**Issue by Nov1st2k10** [nonamecrackers2/crackers-wither-storm-mod#1257] opened 2023-06-30 00:54 UTC
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on
1.19.4
**Mod version**
The version of the mod you are using
3.2.1.3
**Describe the bug**
Amulet painting is unable to be placed

**To Reproduce**
1. Get a 'painting'
2. Make a 2 block tall 1 block wide wall
3. Place painting on wall
4. Amulet painting cant get placed

**Crash Reports / Logs**
Crash reports / logs hosted on pastebin, gist, etc.

**Is OptiFine installed?**
Specify if you're using OptiFine
No
**Screenshots**
![image](https://github.com/nonamecrackers2/crackers-wither-storm-mod/assets/106888663/a4e7b70b-5bf3-449f-aab2-2d6eb8a3b4ce)

texture for unplacable painting
you can find the texture for the painting at witherstormmod/assets/witherstormmod/textures/painting/amulet.png

**Comment by LocalWaterCreeper911911** [comment] 2023-07-01 15:36
Was unable to reproduce this in 1.19.4, the painting is placed just fine.

**Comment by Nov1st2k10** [comment] 2023-07-01 21:42
@LocalWaterCreeper911911 how were you able to place it? are you sure you're on 1.19.4? not 1.19.2 or anything, because i do believe the modded paintings cannot be placed due to the changes with paintings in 1.19.4 so i don't understand how you would have gotten it working

**Comment by LocalWaterCreeper911911** [comment] 2023-07-02 04:19
> @LocalWaterCreeper911911 how were you able to place it? are you sure you're on 1.19.4? not 1.19.2 or anything, because i do believe the modded paintings cannot be placed due to the changes with paintings in 1.19.4 so i don't understand how you would have gotten it working

1. Its 1.19.4 with experimental features turned ON.

2. amulet painting is in creative menu:

Go to setting and search for setting called 'operator utilites' and turn it on
then go to creative menu and see a button with command block on it, click it
there are 4 vanilla paintings and 1 cwsm painting, so yeah
i tried placing this painting and it was placed just fine

**Comment by nonamecrackers2** [comment] 2023-07-04 17:47
Most players won't be playing with experimental features on. Checked and can confirm this bug exists.

**Comment by nonamecrackers2** [comment] 2023-08-19 01:47
Will be fixed in the next 1.19.4/1.20.1 release

**Closed as completed by nonamecrackers2** 2023-08-19 01:47 UTC
Labels: Bug/Errors, 1.19.4
