### ISSUE TITLE
[Suggestion]: Tractor Beam Mob Spinning

### ISSUE THREAD

**Issue by RealPenguinMonkey** [nonamecrackers2/crackers-wither-storm-mod#2180] opened 2024-08-31 01:41 UTC
### Guidelines

- [X] By checking this box, I am saying that I have read the guidelines and believe to be following them to the best of my ability

### Description of feature request

When the Wither Storm picks up a mob, the mob should slowly spin in a random direction. I think this would help make the Wither Storm's Tractor Beams seem like more of a threat!

**Comment by TaintedBlock** [comment] 2024-08-31 01:46
duplicate of https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1055

**Comment by Herobrine982950291** [comment] 2024-08-31 16:24
#1055

**Closed as not planned** 2024-09-02 01:46 UTC
Labels: Duplicate, Suggestion

**Comment by RealPenguinMonkey** [comment] 2024-09-05 22:44
oh i didnt know lol sorry
