### ISSUE TITLE
Chunks breaking

### ISSUE THREAD

**Issue by Alpha-Rikhiram-And-Airelephant9664** [nonamecrackers2/crackers-wither-storm-mod#998] opened 2023-03-06 21:40 UTC
It's me alpha reporting this time
Not air

Basically the chunks with the wither storm in 2.2 sometimes break and cause the player to go into a void sort of state
The only way to fix this is by /killing yourself

Idk how to fix this myself because it's also giving Me trouble

Minecraft version: 1.18.2

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment] 2023-03-06 21:41
Also the wither storm despawns sometimes and I'm guessing this is related to this bug

**Comment by Globalfirestorm10** [comment] 2023-03-06 23:18
Alpha, mind actually filling out the bug report template for once? It's hard to identify the root cause of your problem when you don't provide us with things such as reproduction steps for the bugs listed, screenshots, videos, etc

**Comment by myron-obsolete-account** [comment] 2023-03-07 15:35
> Alpha, mind actually filling out the bug report template for once? It's hard to identify the root cause of your problem when you don't provide us with things such as reproduction steps for the bugs listed, screenshots, videos, etc

how many people didn't fill out the template now? was it 3 or 4?

**Comment by nonamecrackers2** [comment] 2023-03-07 17:08
Please fill in the template

**Comment by myron-obsolete-account** [comment] 2023-03-07 17:20
@nonamecrackers2 I think I know how to fix this issue and get rid of lazy people
I don't know how or if you can even do this or if you need to reach something or whatever but I think an actual issue form should solve the problem
The devs from the Create Mod are doing the same thing
![image](https://user-images.githubusercontent.com/53058491/223499057-3927192e-6aac-4405-b83e-c872acdbf586.png)
Instead of text headers it's actually multiple smaller text boxes to fill

**Comment by Globalfirestorm10** [comment] 2023-03-07 18:05
> @nonamecrackers2 I think I know how to fix this issue and get rid of lazy people
> 
> I don't know how or if you can even do this or if you need to reach something or whatever but I think an actual issue form should solve the problem
> 
> The devs from the Create Mod are doing the same thing
> 
> ![image](https://user-images.githubusercontent.com/53058491/223499057-3927192e-6aac-4405-b83e-c872acdbf586.png)
> 
> Instead of text headers it's actually multiple smaller text boxes to fill
> 
> 

id recommend you do this as well, as many other creators utilize this already

**Comment by nonamecrackers2** [comment] 2023-03-08 17:02
Interesting, didn’t know you could do text boxes. Will look into it, thanks!

**Comment by myron-obsolete-account** [comment] 2023-03-08 17:49
Yah I have no idea how to do that but you're welcome.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment] 2023-03-09 19:03
> Alpha, mind actually filling out the bug report template for once? It's hard to identify the root cause of your problem when you don't provide us with things such as reproduction steps for the bugs listed, screenshots, videos, etc

Ok
I used to do this but for some reason now I don't
I'll be sure to do it agian
If you see some of my other posts I did do this

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment] 2023-03-09 19:07
> Alpha, mind actually filling out the bug report template for once? It's hard to identify the root cause of your problem when you don't provide us with things such as reproduction steps for the bugs listed, screenshots, videos, etc

Also the reason why I don't send screenshots is because I'm probably reporting this late at night because it happened earlier and I'm using a phone anyway so it's a bit difficult transferring the screenshots

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment] 2023-03-09 19:07
> > Alpha, mind actually filling out the bug report template for once? It's hard to identify the root cause of your problem when you don't provide us with things such as reproduction steps for the bugs listed, screenshots, videos, etc
> 
> how many people didn't fill out the template now? was it 3 or 4?

Lots more pal. I see basically everyone here not use the template

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment] 2023-03-09 19:10
> @nonamecrackers2 I think I know how to fix this issue and get rid of lazy people I don't know how or if you can even do this or if you need to reach something or whatever but I think an actual issue form should solve the problem The devs from the Create Mod are doing the same thing ![image](https://user-images.githubusercontent.com/53058491/223499057-3927192e-6aac-4405-b83e-c872acdbf586.png) Instead of text headers it's actually multiple smaller text boxes to fill

I'm clueless with that

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment] 2023-03-14 19:05
Give me a few moments
I'll grab the template and fill it in here

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment] 2023-03-14 19:10
> 

***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2

**Mod version**
2.2

**Describe the bug**
The wither storm's chunk loading breaks causing you to enter a glitched state where you can't move and can't see blocks or mobs, the only way to fix this is with /Kill

**To Reproduce**
Steps to reproduce the behavior:
1. Spawn a witherstorm (preferably a few but I managed to get the glitch to work with only one in a survival world before)
2. See error
3. if it dosent glitch tell me

**Crash Reports / Logs**
It's not a crash

**Is OptiFine installed?**
Nah pal.

**Screenshots**
If applicable, add screenshots to help explain your problem.
Give me a moment I'm obtaining screenshots at the time this is sent.

**Comment by Alpha-Rikhiram-And-Airelephant9664** [comment] 2023-03-14 19:11
> Please fill in the template

***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
1.18.2

**Mod version**
2.2

**Describe the bug**
The wither storm's chunk loading breaks causing you to enter a glitched state where you can't move and can't see blocks or mobs, the only way to fix this is with /Kill

**To Reproduce**
Steps to reproduce the behavior:
1. Spawn a witherstorm (preferably a few but I managed to get the glitch to work with only one in a survival world before)
2. See error
3. if it dosent glitch tell me

**Crash Reports / Logs**
It's not a crash

**Is OptiFine installed?**
Nah.

**Screenshots**
If applicable, add screenshots to help explain your problem.
Give me a moment I'm obtaining screenshots at the time this is sent.

**Comment by nonamecrackers2** [comment] 2023-08-18 23:28
This is extremely late, but if you could add screenshots it'd be most appreciated.

**Comment by nonamecrackers2** [comment] 2023-10-06 18:20
Closing until more information is given. If you do see this, I'd make a new bug report since this one is very chaotic.

**Closed as not planned by nonamecrackers2** 2023-10-06 18:20 UTC
Labels: Bug/Errors, More Info Needed, 1.18.2
