### ISSUE TITLE
When in a hollow or closed off area (if there is a block above the Wither Storm), it floats to the very top of the structure (interior)

### ISSUE THREAD

**Issue by C182MC** [nonamecrackers2/crackers-wither-storm-mod#1002] opened 2023-03-07 23:34 UTC
The Wither Storm's flying abilities aren't as intended when comparing to Minecraft: Story Mode. When the Wither Storm was summoned in the game, it never flew to the absolute very top of a hollow area, (e.g a dome of glass or obsidian cathedral). 

The Wither Storm shouldn't be able to fly up to the absolute very top of a hollow area until it reaches destroyer form and destroys the surrounding area by wrecking the area with its massive body and tentacles.

In hollow areas, the Storm should float the same exact height above the ground as is if there was no blocks above the Wither Storm or the Wither Storm is in a hollow area.

![Screenshot (1563)](https://user-images.githubusercontent.com/127260955/223579664-96da6450-6037-40d8-9ff9-c86d7a6b9495.png)

**Comment by Globalfirestorm10** [comment] 2023-03-08 13:34
Please fill out the template next time, and this is a known bug, idk if theres a fix for this

**Comment by nonamecrackers2** [comment] 2023-03-08 17:07
Eh the information provided is enough, I don’t need you guys to be enforcing template filled out-ness but I appreciate the effort :). I should know the reason behind this though.

**Comment by Globalfirestorm10** [comment] 2023-03-09 13:08
IIRC, I think this happens in the nether as well

**Comment by myron-obsolete-account** [comment] 2023-03-09 13:30
> IIRC, I think this happens in the nether as well

I can confirm this

**Comment by FrozenDragon0** [comment] 2023-03-10 01:34
> IIRC, I think this happens in the nether as well

Ye it does due to the ceiling.

**Comment by Globalfirestorm10** [comment] 2023-03-10 01:52
then IG thats whats happening here?

**Comment by humzahre** [comment] 2023-03-11 16:39
This bug Also happened in older versions. (1.19.2 etc)

**Comment by GrandmaPork** [comment] 2023-03-21 23:21
is this not just what the wither does? It didn't do this in mcsm because they wanted to make it cinematic

**Comment by BluePineappleGuy** [comment] 2023-03-23 12:57
well the wither storm shouldn't just fly to the top. personally it would be more epic to have it fly around closer to the ground then go flying up wrecking everything.

**Comment by nonamecrackers2** [comment] 2023-03-27 23:22
Will be fixed in 2.2.1/3.2.1

**Closed as completed by nonamecrackers2** 2023-03-27 23:22 UTC
Labels: Bug/Errors, 1.18.2, 1.19.3
