### ISSUE TITLE
Game keeps crashing when the world is done loading

### ISSUE THREAD

**Issue by Greg727** [nonamecrackers2/crackers-wither-storm-mod#925] opened 2023-02-17 21:25 UTC
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on is 1.19.2

**Mod version**
The version of the mod I am using is 1.19.2-3.1.1

**Describe the bug**
The game loads just fine, but whenever 

**To Reproduce**
1. Load the game
2. Create a World
3. The Crash happens

**Crash Reports / Logs**
[crash-2023-02-17_16.17.22-client.txt](https://github.com/nonamecrackers2/crackers-wither-storm-mod/files/10771786/crash-2023-02-17_16.17.22-client.txt)

**Comment by Globalfirestorm10** [comment] 2023-02-18 00:10
duplicate of #885, please close. In the mean time, use the recommended version of CWSM

**Closed as completed** 2023-02-19 18:41 UTC
Labels: Duplicate
