### ISSUE TITLE
Tainted Cobblestone & Stone are unable to be mined properly

### ISSUE THREAD

**Issue by GoldSlimeling91** [nonamecrackers2/crackers-wither-storm-mod#681] opened 2022-09-30 19:24 UTC
**Minecraft version**
1.19.2

**Mod version**
3.1

**Describe the bug**
Tainted Cobblestone and Tainted Stone are extremely difficult to mine, as pickaxes do not affect it's speed in any way, these blocks will also never drop themselves in item form when mined.

**To Reproduce**
1. Place either Tainted Cobblestone or Tainted Stone
2. Give yourself a pickaxe of any kind and start mining
3. Takes ages to break it
4. Doesn't drop item upon breaking

This bug can be potentially fixed by adding these blocks to the 'mineable/pickaxe' block tag, as they are not in this block tag in the current version.
![2022-09-30_15 22 49](https://user-images.githubusercontent.com/111310936/193342350-bbb4602e-ecd1-4ff1-9098-c84b84df73db.png)

**Comment by Asteroid4** [comment] 2022-10-02 13:10
I noticed this too, I thought it was intended.

**Comment by EnderPlays123** [comment] 2022-10-02 13:11
#445

**Comment by nonamecrackers2** [comment] 2022-10-16 00:32
Will be fixed in the latest update.

**Closed as completed by nonamecrackers2** 2022-10-16 00:32 UTC
Labels: Bug/Errors, 1.18.2, 1.19
