### ISSUE TITLE
(1.18.2) Aternos server not working

### ISSUE THREAD

**Issue by Waomois** [nonamecrackers2/crackers-wither-storm-mod#79] opened 2022-06-12 18:23 UTC
Ok for some reason every time i start an aternos server with the 1.18.2 version of the mod. It basically just crashes everytime and gives me this as a crash report https://mclo.gs/0QEC0jd

**Comment by nonamecrackers2** [comment] 2022-06-12 19:00
Try using a different forge version. May not work, but give it a shot.

**Comment by Waomois** [comment] 2022-06-12 19:29
Tried but didn't work. It may be because of the house where you can summon the wither storm but idk. Edit: wait do you mean like a version other than 1.18.2 or a different forge version of 1.18.2?

**Comment by nonamecrackers2** [comment] 2022-06-12 19:53
Different forge version of 1.18.2 sorry

**Comment by Waomois** [comment] 2022-06-12 19:56
Ok but is there any way you can fix it or i have to stick with 1.16.5 for starting servers?

**Comment by cielospasteles** [comment] 2022-06-12 20:56
I'm having this same issue as well. Using Exaroton which is a pay-as-you-go version of Aternos.
Trying to make a modded server for me and some friends and upon making a new world it just crashes.
I think the issue is the house that generates with the mod, because after I launched the server without it, then put it back in, it booted up just fine.

**Comment by nonamecrackers2** [comment] 2022-06-12 21:12
It’s some sort of weird dependency issue and may be with just any dedicated server. I’ll have to investigate later today.

**Comment by nonamecrackers2** [comment] 2022-06-12 21:12
And yes, for now just stick with 1.16.5

**Comment by Waomois** [comment] 2022-06-12 22:01
ok then

**Comment by nonamecrackers2** [comment] 2022-06-13 02:54
It appears I was using a different class from a different library that Aternos and other hosts don't specifically support. Should be fixed in the next update.

**Comment by nonamecrackers2** [comment] 2022-06-14 13:26
Just noticed this wasn’t actually fixed.

**Closed as completed** 2022-06-14 18:58 UTC
Labels: Bug/Errors, 1.18.2
