### ISSUE TITLE
Tractor beams seen through ground when going through portal

### ISSUE THREAD

**Issue by darkheart78** [nonamecrackers2/crackers-wither-storm-mod#1115] opened 2023-04-15 18:20 UTC
***Please check the guidelines before submitting:*** https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/217

**Minecraft version**
The version of Minecraft the mod is running on
1.19.3

**Mod version**
The version of the mod you are using
3.2.1.1

**Describe the bug**
whenever you are in a portal the storm beams go through the ground

**To Reproduce**

1. Wither storm at phase 4 or more
2. go far away
3. make nether portal
4. go into portal
5. get the naeusaua effect
6. look at the storm

**Is OptiFine installed?**
yes but i dont think its why (prove me wrong)

**Screenshots**
(https://user-images.githubusercontent.com/128404590/232246705-9ff76416-3296-426e-992e-5fd89573d352.png)

**Comment by myron-obsolete-account** [comment] 2023-04-15 21:30
does this also happen when you look through the portal block?

**Comment by darkheart78** [comment] 2023-04-17 00:49
no

**Comment by nonamecrackers2** [comment] 2023-08-21 04:22
Unable to reproduce. This should be fixed in the version you claim to be using.

**Closed as not planned by nonamecrackers2** 2023-08-21 04:22 UTC
Labels: Bug/Errors, Can't Reproduce, 1.19.3
