### ISSUE TITLE
Better Block Clusters

### ISSUE THREAD

**Issue by LucasDotje** [nonamecrackers2/crackers-wither-storm-mod#909] opened 2023-02-11 11:23 UTC
Please Make The Block Clusters Better, Like Adding That The Wither Storm Picks The Whole Tree Instead Half The Tree

**Comment by myron-obsolete-account** [comment] 2023-02-11 14:47
duplicate of #811, please close this

**Comment by Isoknight** [comment] 2023-02-11 16:34
> duplicate of #811, please close this

From what i'm seeing, that's for Dynamic Trees. Not basegame trees.

**Comment by Globalfirestorm10** [comment] 2023-02-11 18:30
Kid (Lucas, not Moron), what part of "check to make sure that this suggestion hasn't been suggested already" do you not understand? Get it through your thick skull

**Comment by myron-obsolete-account** [comment] 2023-02-11 18:33
man's skull is bigger than the entire universe

**Comment by LucasDotje** [comment] 2023-02-11 18:51
Do I Really Need To Read Every Suggestion Before Posting?

**Comment by Globalfirestorm10** [comment] 2023-02-11 18:59
> 
> 
> Do I Really Need To Read Every Suggestion Before Posting?
> 
> 

you don't, just make sure to change the open catergory to "all", then search your suggestion (or keywords of it). You can also take a look at the commonly requested features list, and the confirmed features on discord

**Comment by LucasDotje** [comment] 2023-02-11 19:02
I Searched For The Word : Cluster ,  And I Didn't Saw Anything Like This In The Title

**Comment by Isoknight** [comment] 2023-02-11 19:31
Search for the idea that you wanted to suggest, not just the title.

**Comment by myron-obsolete-account** [comment] 2023-02-13 13:14
@LucasDotje planning on closing this someday?

**Comment by LucasDotje** [comment] 2023-02-13 15:46
How To Do That

**Comment by myron-obsolete-account** [comment] 2023-02-13 16:17
![image](https://user-images.githubusercontent.com/53058491/218512502-bd43fb11-754d-44d3-9ce0-295aa4622d6e.png)

**Closed as completed** 2023-02-13 16:36 UTC
Labels: Suggestion
