### ISSUE TITLE
evolution attribute modifier not working (not sure if im missing something or it doesnt work)

### ISSUE THREAD

**Issue by personmhmyes** [nonamecrackers2/crackers-wither-storm-mod#308] opened 2022-07-21 10:18 UTC
**Minecraft version**
1.19
**Mod version**
witherstormmod-1.19-3.0-beta.jar (curseforge)

**Describe the bug**
i load up a new world with the mod i make the settings i enjoy one of them is the evolution attribute modifier because i dont wanna wait to long and im aware of the command to make the storm bigger but i just wanted to be fast evolving and i go to the house and spawn the storm in at the top when he spawns he sucks up everything fine but he takes the same amount of time to evolve i also go to the commands and use the witherstormmod funtion to make it evolve faster i tried 3 and 0.1 it doesnt change even on world reload and spawning a new storm to so if that refreshes it which it doesnt but if i spawn the storm using console all the changes work and he goes from phase 0 to the end of phase 5 in 20 seconds (estimated) so in conclusion only the console lets the witherstorm evolve faster

**To Reproduce**
1. Go to 'the W in the settings '
2. Click on 'click on the button'
3. Scroll down to 'evolution attribute modifier and set it to 0.01 along with using the command /witherstormmod evolutionspeed @e[type=witherstormmod:wither_storm,limit=1] 3 or 0.1 then spawn it using commands and building one and you see the massive difference'

**Crash Reports / Logs**
no crashes / logs hosted on pastebin, gist, etc.

**Screenshots**

**Comment by nonamecrackers2** [comment] 2022-09-21 22:43
I don't see anything wrong. Not sure what exactly I'm looking for, but both the config value (after world reload of course) and the /witherstormmod evolutionSpeed command both work fine (don't even have to resummon the Wither Storm). Closing until the issue is found, if there is one. Thanks for your time.

**Closed as completed by nonamecrackers2** 2022-09-21 22:43 UTC
Labels: Bug/Errors, Can't Reproduce, 1.19
